### ISSUE TITLE
服を買いに行きませんか

### ISSUE THREAD

**Issue by abap34** [momeemt/momeemt#10]
椎名さんが秋服が欲しいそうです。僕もそう思います。買いに行きませんか？

**Comment by s7tya** [comment]
abap34 が大岡山で凍えてるらしいです 彼は _shy_ なので人がいないとお店に入れません

**Comment by s7tya** [comment]
巻き添え @aumyf

**Comment by AumyF** [comment]
町田のユニクロならいいよ

**Comment by momeemt** [comment]
あーいいね　10月中旬とかなら割と暇　平日はほぼ授業

**Comment by abap34** [comment]
明後日か明明後日は？

**Comment by momeemt** [comment]
お金無さすぎるから10月以降が良いです

**Comment by s7tya** [comment]
急すぎる　ユニクロのオンラインで買え

**Comment by abap34** [comment]
オンラインで買うならもうとっくに買ってるんだよな、というね

**Comment by momeemt** [comment]
そもそもオタク4人で服買いに行くの、なんらかの罪に問われないのか

**Comment by abap34** [comment]
じゃあ俺が画面共有しながらオンラインショップで服買うからコメントして

**Comment by s7tya** [comment]
abapさんが限度額1万のVプリカ3枚買って3人それぞれおすすめの服買うってどう？ウケるから

**Comment by AumyF** [comment]
オモロ

**Comment by AumyF** [comment]
一日考えてたけどグレーのパーカーしか思いつかなかったな

**Comment by s7tya** [comment]
白Tに黒のチノパン

**Comment by s7tya** [comment]
三万円分…

**Comment by momeemt** [comment]
abapがスケールアウトしても安心

**Comment by AumyF** [comment]
するんだ

**Comment by momeemt** [comment]
買いたいのは山々だったんですけど一年を通して壊れたスケジュール感を信じていたら炎上したので無理そうです　冬また誘ってください

**Comment by abap34** [comment]
ごめん今日渋谷で買っちゃった
![image](https://github.com/momeemt/momeemt/assets/53076594/88a54421-77a9-4509-8bd4-a851a6e1c1cb)
