### ISSUE TITLE
きき米をする

### ISSUE THREAD

**Issue by s7tya** [momeemt/momeemt#11]
@abap34 @aumyf @momeemt

## 候補者

- 安めの米 + つくばの水道水(浄水器なし)
- 安めの米 + ペットボトルの水
- さとうのご飯
- 雪椿(高級米)

ペットボトルの水で炊いたら美味しかった気がする。一方水道水と浄水器とペットボトルの水の違いはわからないから謎。

**Comment by AumyF** [comment]
炊きたてはベシャベシャでおいしくないしそもそも熱すぎて味どころではない

**Comment by momeemt** [comment]
かわいそうだけど食べてもらうよ

**Comment by s7tya** [comment]
HELP WANTED: 米並列炊きソリューション

**Comment by momeemt** [comment]
純粋に炊飯器を持ち寄るのでは難しいのでしょうか

**Comment by momeemt** [comment]
https://www.rentio.jp/t/genre/kitchen/rice-cooker

レンタルすると高いので、友人から借りるというのもあります

**Comment by abap34** [comment]
神奈川の水道水もいる？

**Comment by momeemt** [comment]
はい

**Comment by s7tya** [comment]
や、オタクが「炊いて時間経ったら違うから🥸」って言いそうかなって…

**Comment by abap34** [comment]
会話通じてる？

**Comment by AumyF** [comment]
炊飯器って何台並列で炊いたらブレーカー落ちるんすかね

**Comment by s7tya** [comment]
電源もレンタルしよう

**Comment by abap34** [comment]
焚き火案

**Comment by momeemt** [comment]
自然が多いのって何しても許される免罪符ではないよ

**Comment by abap34** [comment]
大学に焚き火できるところないの？

**Comment by momeemt** [comment]
僕は大学についてはよく知らないので @s7tya が回答してくれると思います

**Comment by momeemt** [comment]
いやごめん　そもそもこれ日程決まってましたっけ

**Comment by s7tya** [comment]
決まってない 火をつけられるところ流石に学内にはないけど、それなら普通にモミ家で焚き火したらいい気がする

**Comment by abap34** [comment]
モミ家で (手段の用法)

https://japanese-language-education.com/bunpo7/

**Comment by momeemt** [comment]
𝑫𝒆𝒂𝒓 𝒂𝒃𝒂𝒑,

𝒏𝒊𝒄𝒆 𝒉𝒖𝒎𝒐𝒓

𝑹𝒆𝒈𝒂𝒓𝒅𝒔,
𝒎𝒐𝒎𝒆𝒆𝒎𝒕

**Comment by s7tya** [comment]
日本語勉強中の学生とユーモア鑑定団だ

**Comment by AumyF** [comment]
ちょっと見ない間にめっちゃ話進んでた

**Comment by s7tya** [comment]
本質的には何も進んでない　形だけのFAKE集団

**Comment by momeemt** [comment]
安易に本質を語らないでください

**Comment by AumyF** [comment]
本当に形だけの集団だったらいつにしますか？あ、24日で。承知しました。で集まって米食って終わっている

**Comment by momeemt** [comment]
11/26までは忙しいので厳しくて、12/16ごろからも期末対応のため厳しいです

そのほか、12/3, 12/7, 12/13にすでに予定があります

**Comment by abap34** [comment]
たぶん 既に俺の行ける日との共通部分が12/2,12/4, 12/5,12/6 しかない

**Comment by momeemt** [comment]
2024年初イベントになってしまう可能性出てきた

**Comment by s7tya** [comment]
12/2あいてる

**Comment by s7tya** [comment]
米って和のものだから三が日にお参りしてから食べるといいらしいよ

**Comment by momeemt** [comment]
笑　和だけに...............

**Comment by AumyF** [comment]
炒飯は日本の食べ物という主張ですか？帝国主義？

**Comment by s7tya** [comment]
和は全ての国を包含する存在だからね

**Comment by s7tya** [comment]
雪椿買った
家につや姫とはえぬきある、もみ家に普通の米はあるよねたぶん
当日おかずとさとうのご飯は買いに行こう

**Comment by s7tya** [comment]
@aumy_f が大丈夫なら12/2で

**Comment by AumyF** [comment]
大丈夫と思われるので12/2

**Comment by s7tya** [comment]
おかずに冷凍餃子大量購入して餃子パーティー

**Comment by momeemt** [comment]
ノイズすぎない？

**Comment by momeemt** [comment]
餃子

**Comment by momeemt** [comment]
お米の味を比較するにしては

**Comment by s7tya** [comment]
wwwわかるよ
