### ISSUE TITLE
🎍𝗛𝗮𝗽𝗽𝘆 𝗡𝗲𝘄 𝗬𝗲𝗮𝗿🎍

### ISSUE THREAD

**Issue by s7tya** [momeemt/momeemt#12]
あけました

**Comment by AumyF** [comment]
おめでとうございます❗

**Comment by momeemt** [comment]
あけおめ〜

**Comment by s7tya** [comment]
年が開けたから開いたissue、閉じたら締まるかな 良いお年を〜！ 2025年

**Comment by momeemt** [comment]
@abap34 俺らは2025年で待ってる

**Comment by abap34** [comment]
![image](https://github.com/momeemt/momeemt/assets/53076594/d4cd3572-5050-440a-9150-dbfac4175d03)

**Comment by abap34** [comment]
俺はまだ2023

**Comment by momeemt** [comment]
間違えすぎ
