### ISSUE TITLE
新年会　とりや

### ISSUE THREAD

**Issue by s7tya** [momeemt/momeemt#13]
w/ @abap34 @aumyf

**Comment by momeemt** [comment]
17以降希望

**Comment by AumyF** [comment]
今のところ01月は26, 28が空いてません

**Comment by abap34** [comment]
2月最初テストで予定も詰まってるから 2月なかばとかがいい

**Comment by abap34** [comment]
2月なかば以降

**Comment by AumyF** [comment]
もう新年会じゃなくなった

**Comment by momeemt** [comment]
2月なかば秋C期末なので2月下旬希望で...

**Comment by abap34** [comment]
じゃあもう 3/4 以降にしてくれ

**Comment by s7tya** [comment]
3月あんまり空いてないが、4月は普通に授業多いからあるとして土日

**Comment by s7tya** [comment]
2/17, 18とかで丸いんじゃない？

**Comment by momeemt** [comment]
ごめん2/17, 18予定入ってます、、

**Comment by AumyF** [comment]
20241Qに収まるかもわからんなってきたね

**Comment by s7tya** [comment]
関係ないパソコンをやめてテストに専念できると誓える人間だけがテスト期間を主張しなさい

**Comment by momeemt** [comment]
じゃあまあ、引き続き主張させていただきますね...

**Comment by momeemt** [comment]
あと普通に忘れてたんだけど秋Cに期末科目は1つもなかった

**Comment by abap34** [comment]
ちなみに別の俺の誕生会もあってそれも普通にとりやの予定だからこのままだと俺目線でとりや行きすぎなんですけど

**Comment by AumyF** [comment]
日程を決めないと真にとりや行きすぎかは判定できないと思います

**Comment by momeemt** [comment]
鶏持ち寄ってネオとりや開店、鳥刺しを再発明

**Comment by AumyF** [comment]
Libreとりや、鶏を AS IS WITHOUT WARRANTY で提供

**Comment by s7tya** [comment]
> あと普通に忘れてたんだけど秋Cに期末科目は1つもなかった

じゃあ1月末がよさそう？

**Comment by s7tya** [comment]
21, 27, 30とかどう

**Comment by s7tya** [comment]
鳥買って育てる　俺がとりやだ

**Comment by AumyF** [comment]
てかとりやの鳥刺しってあれ安心して食べていいものなの？前回行ったあとけっこう1週間ぐらい怯えながら暮らしてたんだけど

**Comment by momeemt** [comment]
> > あと普通に忘れてたんだけど秋Cに期末科目は1つもなかった
> 
> じゃあ1月末がよさそう？

いや1月末はabapの試験でダメだったと思う 筑波勢の期末が無くて行けるようになるのは2月半ば

**Comment by momeemt** [comment]
一応、27,30は空いてます

**Comment by s7tya** [comment]
@abap34 1/27か1/30あいてる？

**Comment by abap34** [comment]
まぁ原理的には一応空いてるけどマジでテスト前なんだよな〜　JuliaTokyo もあるし

**Comment by s7tya** [comment]
おしまい

**Comment by AumyF** [comment]
先のほうだと今のところ02/16, 03/08が空いてないです

**Comment by AumyF** [comment]
ふつうに3月なら予定合うんじゃないの

**Comment by momeemt** [comment]
次の誕生日までお預け

**Comment by AumyF** [comment]
2025？

**Comment by momeemt** [comment]
2025に乞うご期待

**Comment by abap34** [comment]
3月なら 大体いけるけど

**Comment by abap34** [comment]
そもそも誕生日会なら誕生日前後にやれや

**Comment by momeemt** [comment]
誕生日会と銘打っておきながらなんだけど今回は多分とりやが本質なのでは

**Comment by AumyF** [comment]
誕生日会で誕生日を祝うことが本質なことなくないですか？

**Comment by s7tya** [comment]
一月も二月も開いてないっていうから渋々そうなってるのに傲慢な犬　わからせてやらなきゃ

**Comment by momeemt** [comment]
友達と仲良くなろう

**Comment by AumyF** [comment]
続けるならreopenしよう

**Comment by abap34** [comment]
普通に誕生日に大学の友達と　とりや行く約束してるから　大岡山のあそこの飲食店街の別の店行きたい　別に大岡山じゃなくてもいいけど

**Comment by s7tya** [comment]
とりやでもなくて新年会でもなかったら開催意義なくない？

**Comment by AumyF** [comment]
とりや好きすぎない？

**Comment by momeemt** [comment]
かなり分かる、時期ずれてもいいからとにかくとりやに行きたい

**Comment by AumyF** [comment]
@abap34 の最短とりや可能間隔ってどれくらいですか？

**Comment by abap34** [comment]
せめて 2w

**Comment by s7tya** [comment]
3/20から車校

**Comment by AumyF** [comment]
予定は詰まっていれば詰まっているほどよい

**Comment by momeemt** [comment]
じゃあまあ

- #14 
- #15 

に分割してcloseします
