### ISSUE TITLE
新年会　*

### ISSUE THREAD

**Issue by momeemt** [momeemt/momeemt#14]

**Comment by AumyF** [comment]
とはいえ新年会って感じの時期に開催できるんですか？

**Comment by momeemt** [comment]
すでに新年会シーズンではないと思う

**Comment by AumyF** [comment]
まったく正しい

**Comment by momeemt** [comment]
一方で新年会のシーズンは俺たちに決める自由があるという声もあり、それも無視できないので、今回はそちらを採用します

**Comment by AumyF** [comment]
とりあえず全員集まれる集まれる一番早い日はいつなんですか　結局abap誕周辺？

**Comment by momeemt** [comment]
車校の人いるしabap誕生日周辺を除いた2月下旬〜3/20あたりなのでは？　2月末新年会どうですか @AumyF @s7tya @abap34

**Comment by AumyF** [comment]
今のところ03/08が空いてなくて、02/28空くかどうかは今週中に決めます　その他の土日水は一日暇で平日は夜暇です

**Comment by abap34** [comment]
2/27~29
3/20~ が無理かな

**Comment by s7tya** [comment]
2末場合によってはインターンある

**Comment by s7tya** [comment]
3/17 3/18 のどちらかなど

**Comment by momeemt** [comment]
18厳しいので17なら

**Comment by s7tya** [comment]
@AumyF @abap34 3/17

**Comment by s7tya** [comment]
実はこちらも解決

**Comment by momeemt** [comment]
こっちを閉じるべきだった
