### ISSUE TITLE
筑波大学AC入試についてのご連絡

### ISSUE THREAD

**Issue by kbclabmemberm** [momeemt/momeemt#16]
突然の連絡失礼します。araと申します。
2024年度の筑波大学情報学群情報科学類のAC入試を受験しようと考えて、noteの記事を見て連絡させていただきました。
もしよろしければ、自己推薦書を見せていただけませんでしょうか。
AC入試を受験した先輩などが周りにおらず、どうやって進めていけばいいのか悩んでいます。

**Comment by momeemt** [comment]
@Araryu09 こちら、リポジトリに招待送りましたのでGitHubに登録したメールアドレスをご確認ください。何か具体的な質問があった場合はそちらにIssueを立てていただくか、 me@momee.mt にご連絡いただければ返信します。応援しています！
