### ISSUE TITLE
筑波大学AC

### ISSUE THREAD

**Issue by atprunya** [momeemt/momeemt#19]
@momeemt お忙しい中、突然のご連絡失礼致します。
現在、筑波大学情報学群のAC入試に向けて資料作成をしている、高校三年の阿曽というものです。資料作成にあたり、ご執筆されたnoteを参考にしています。情報公開ありがとうございます。
現在、レイアウトや論理の構成に困っていて、参考にしたいという気持ちがあるので、もしよろしければ自己推薦書のレポジトリに招待いただき、閲覧させていただきたいです。

お忙しい中申し訳ございません。よろしくお願いいたします。

**Comment by momeemt** [comment]
@suzukaze-pix こんにちは、リポジトリに招待しました。また何か質問などがあればお気軽にリポジトリのIssues、または me@momee.mt にご連絡ください。入試が上手くいくよう、応援しております！

**Comment by atprunya** [comment]
ありがとうとうございます！助かります。後輩になれるように頑張ります
