### ISSUE TITLE
飯行かん？

### ISSUE THREAD

**Issue by AumyF** [momeemt/momeemt#2]
つくば (以外でも 🉑) で飯を喰いながら計算機の話がしたくなってきたんで飯行こうぜ飯

**Comment by momeemt** [comment]
いいね　行きたい
ラーメン、長時間の会話に向いてないから肉でも焼く？

**Comment by AumyF** [comment]
肉いいね　直近だと2月の1, 4, 5が空き　他パーソン呼ぶなら4か5？

**Comment by momeemt** [comment]
2/4空きなのでそこで！

**Comment by AumyF** [comment]
拝承

**Comment by abap34** [comment]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/53076594/215389939-4771b371-d4b3-454e-8bdf-91f55344f060.png">

**Comment by abap34** [comment]
2/9くらいまではとても動ける状況ではない.

**Comment by momeemt** [comment]
字が綺麗だね

**Comment by abap34** [comment]
本気出したらもっと綺麗だよ

**Comment by momeemt** [comment]
最初から出せよ

**Comment by abap34** [comment]
予定立てる時なんてやる気ない時だから

**Comment by momeemt** [comment]
確かにね

**Comment by abap34** [comment]
そっちはテスト期間いつまでなの

**Comment by momeemt** [comment]
なのお

**Comment by abap34** [comment]
^^;

**Comment by momeemt** [comment]
2/17までですね

**Comment by abap34** [comment]
じゃあそれ以降？@momeemt がテストより友達優先なら2/10~が候補になるけど

**Comment by momeemt** [comment]
良いニュースと悪いニュースがあります
- 残念ながら友達は優先されませんでした。
- 試験は2/15で終わりでした

**Comment by abap34** [comment]
ok

**Comment by AumyF** [comment]
ん〜
@puripuri2100 02/04 飯どうすか

**Comment by momeemt** [comment]
ごめん　4日、可能性が消滅したんかと思って予定入れてしまった...

**Comment by puripuri2100** [comment]
いいね
2がつは11・12以外はいつでもOKです（テスト日程等はmomeemtと完全丸被りなはず）

**Comment by AumyF** [comment]
> 2がつは11・12以外はいつでもOKです

@puripuri2100 これは11、12除く土日って解釈であってますか
@momeemt 02/05空いてます？

もみやまが05空いてたら05、そうでなければ19か20になる？

**Comment by puripuri2100** [comment]
> @puripuri2100 これは11、12除く土日って解釈であってますか

- 夜ならば平日含めて11・12除いて何曜日の何日の何時でも大丈夫です
- 昼ならば6・7除いて何曜日の何日の何時でも大丈夫です

**Comment by AumyF** [comment]
厳密定義感謝します

まあ確かに、いうて夜なら平日でもokという話はあるんだよな　僕は月火木金は17次退勤で、水土日はずっと空いてますね

**Comment by AumyF** [comment]
思いつきなんだけど、逆に、回転寿司

**Comment by momeemt** [comment]
月の予定を列挙します
- 5日空いてません
- 15日空いてません
- 平日は木曜日の8:00〜14:00、金曜日の16:00〜が空いてません
- 2/7の12:00〜18:00 空いてません
- 2/16 18:00〜空いてません
- 2/19空いてません
- 2/22 18:00〜空いてません

なので、2/8とかどうでしょうか
ダメなら2/6夜、2/9夜、2/20などがパッと見空いてそう

> 思いつきなんだけど、逆に、回転寿司

かなりありだと思う

**Comment by AumyF** [comment]
~02/08 OK~

昼寿司→夜肉という説もありえる　金は知らん

**Comment by AumyF** [comment]
ちょまってごめん、ドタで本当に申し訳ないんだけど、2/8にFor Tracy Hydeのライブあるわ　解散前に一度は行きたい

とすると次に1日使える日 (おれは一日使えるほうがうれしい) が2/18, 25, 26, 3/1しかない　どうですか @momeemt @puripuri2100

**Comment by momeemt** [comment]
全部空いてるけど19に予定があって体を休めたいから25,26,3/1のどれかがいいなあ

**Comment by puripuri2100** [comment]
3/2の朝から東京で予定があるので3/1は厳しい
2/18, 25, 26のどれかなら大丈夫

**Comment by momeemt** [comment]
26が嬉しいです（24の夜にご飯行くので）

**Comment by AumyF** [comment]
ジャー26にします

**Comment by momeemt** [comment]
東京？つくば？
つくばだと回転寿司の選択肢はスシローくらいで、焼肉の選択肢は牛角か天1の地元の焼肉屋さん（ランチだけまともな値段で夜は学生には厳しそう）、あと2,3店舗はあるけどそっちは行ったことない

**Comment by AumyF** [comment]
めしの入りabilityとおれの行きabilityからすると東京なんだけど、1日どこで消費するかは謎だよね (本屋かも)、つくばならたむろすることができる空間があるけど

**Comment by puripuri2100** [comment]
2日前ですが、結局プランはどうする感じ？

**Comment by AumyF** [comment]
東京エアプなので何も思いつかないんですよね　浅草とか？

**Comment by puripuri2100** [comment]
東京の飯屋、時間帯によって混み具合と価格などがかなりブレるのでそこを確定させたいね

**Comment by puripuri2100** [comment]
浅草なら雑にもんじゃ焼き屋に入れば全てが解決する気がしてきた

**Comment by momeemt** [comment]
https://tabelog.com/tokyo/A1311/A131102/13098970/

こことかどう？賑やかそうだから会話しやすいし、値段も手頃だし、駅からも近い

**Comment by puripuri2100** [comment]
良さそう

**Comment by AumyF** [comment]
良さそう2

**Comment by puripuri2100** [comment]
時間帯っていつになります？
自分の生活リズムの調整が必要な気がしており…

**Comment by AumyF** [comment]
昼？

**Comment by momeemt** [comment]
昼集合が履行される気が全くしないので夕方集合で夜ご飯とかでもいいのでは

**Comment by momeemt** [comment]
あ、しかし月曜日の朝に予定があるので可能なら昼の方がありがたくはあります　そうすると12:00浅草とかになると思うんだけど現実的に可能なのかという

**Comment by puripuri2100** [comment]
12:00浅草了解！
頑張ります（超頑張る）

**Comment by momeemt** [comment]
頑張ります2

**Comment by AumyF** [comment]
頑張ります3

**Comment by puripuri2100** [comment]
@AumyF 頑張っていますか？

**Comment by momeemt** [comment]
@AumyF よくがんばりました
