### ISSUE TITLE
abap飯

### ISSUE THREAD

**Issue by momeemt** [momeemt/momeemt#3]
なんかabapとのご飯が流れてるからそれも決めたい
@abap34

**Comment by momeemt** [comment]
これは春休みがいいかなって感じ

**Comment by abap34** [comment]
そうだね
東京中心部か、@momeemtが帰ってくるタイミングがあれば大井町線田園都市線あたりもあり(まぁ俺がつくばに行ってもいいけど)

**Comment by momeemt** [comment]
まあつくばわざわざお越しになってもなんもあらへんから…
オタクって本巡り以外でどうやって1日潰してるの？カフェで実装？

**Comment by abap34** [comment]
オタクと出かけないから分かんないな

**Comment by momeemt** [comment]
オタクと出かけない人とは一緒にご飯は行けないので今回の話はなかったことに…(^-^;💦

**Comment by abap34** [comment]
結局いつならこっちにいるの？

**Comment by momeemt** [comment]
基本的に今回は帰省しなくて、単発で東京に戻るのでいつでも良いです　冬休みは2/18以降です

**Comment by abap34** [comment]
ok 今週中に予定出します

**Comment by abap34** [comment]
土日希望
ご飯はなんでもいいけどお肉系かな

**Comment by momeemt** [comment]
3/4 or 5 どう？（でも今自分の予定を一切把握してなくて空いてないかもしれないので明日確認してもう一度送ります）
肉了解

**Comment by abap34** [comment]
俺3/4誕生日だから誕プレくれるならいいよ

てか4,5が土日かよ

**Comment by momeemt** [comment]
じゃあ4で　3はめんどくさいので行かない

**Comment by abap34** [comment]
ok.

**Comment by abap34** [comment]
一日空いてるからなんでもいいけど....ディズニー行く？💓

**Comment by momeemt** [comment]
リモート参加で

**Comment by abap34** [comment]
現代っ子だね
