### ISSUE TITLE
ピザパ

### ISSUE THREAD

**Issue by abap34** [momeemt/momeemt#6]
ピザパ at つくば in GW
CC: @s7tya, @AumyF

**Comment by s7tya** [comment]
食べたかった、今日

**Comment by momeemt** [comment]
ごめん今日食べた

**Comment by abap34** [comment]
今日食べたことはGWに食べない理由にはならないのでは.(例えば米は毎日食べますよね?)

**Comment by AumyF** [comment]
金欠なので東京のが助かるという気持ちがあります

**Comment by momeemt** [comment]
折衷案として、回転寿司

**Comment by abap34** [comment]
銀のさらでいいじゃん

**Comment by s7tya** [comment]
モミマウだけ寿司食べてみんなピザパ

**Comment by abap34** [comment]
なぜ回すのか

**Comment by momeemt** [comment]
寿司って回ることで旨味を得てるから回らない寿司って本当に味しないよ

**Comment by abap34** [comment]
じゃあ俺の奢りの回らない寿司はもみやまさん抜きで行ってくるね

**Comment by momeemt** [comment]
前言撤回　おーみーさんが回らない寿司苦手らしいから代わりに僕が行きます

**Comment by AumyF** [comment]
先に日程合わせないとGW終わりそう

**Comment by AumyF** [comment]
回らない寿司全然苦手じゃないしabapさんが奢ってくれるなら全然行くけど全然

**Comment by momeemt** [comment]
3,4,5のどれかなら空いてます、泊まるなら3,4

**Comment by s7tya** [comment]
ここだけの話、4だけあいています
かつ4はおそらく東京にいます‼️

**Comment by AumyF** [comment]
7まで全部空いてます🤘

**Comment by AumyF** [comment]
あいてる∧東京にいる ←？

**Comment by s7tya** [comment]
帰省

**Comment by s7tya** [comment]
@momeemt 6,7を含んだ場合も3,4,5だけですか？

**Comment by momeemt** [comment]
7は空いていますが運が悪いと東京にいる可能性あります

**Comment by s7tya** [comment]
おお、であれば3-7東京に居残って東京で会をするのもありなのかもという気もしなくもないですね
悩ましい

**Comment by momeemt** [comment]
abapがつくばに来たそうな雰囲気出してるけどそうでも無いなら東京でも

**Comment by AumyF** [comment]
abapさんだけつくばからリモート参加すれば良さそう！

**Comment by abap34** [comment]
つくば市行きたすぎたんだけどなぁ

**Comment by momeemt** [comment]
> abapさんだけつくばからリモート参加すれば良さそう！

名案じゃん

**Comment by abap34** [comment]
4に田都のどっかで食うか

**Comment by AumyF** [comment]
abapさんが前に行ってた氷トンカツ気になる

**Comment by s7tya** [comment]
たしかにピザパもつくばも消えてて発足した意義は何も達成されていない形骸化した会合ですね

**Comment by abap34** [comment]
じゃあもうお前ら捨てて俺だけつくばで開発合宿する

**Comment by AumyF** [comment]
どこ泊まんの

**Comment by momeemt** [comment]
流山おおたかの森

**Comment by s7tya** [comment]
モミマウさんの大ウケ回答は一旦置いておいて、4日に東京で良いですか？

**Comment by AumyF** [comment]
なんで -1 なんだよ

**Comment by AumyF** [comment]
モミマウさんの大ウケ回答に-1してるだけか　分かりづれえな

**Comment by momeemt** [comment]
何リアクションも通知されるの？

**Comment by momeemt** [comment]
一瞬で反応されてびっくりした

**Comment by AumyF** [comment]
たまたま開いたタイミングがリアクションつけた直後だっただけらしい

**Comment by momeemt** [comment]
運命的

**Comment by s7tya** [comment]
みんなこまめに見にきて会話してるの終わりすぎる、2023年ですよ

**Comment by s7tya** [comment]
僕もabapさんに対抗して一人でピザパしようかな

**Comment by AumyF** [comment]
二番煎じってことですか？

**Comment by momeemt** [comment]
そうやってすぐ人攻撃するの良くないですよ

**Comment by AumyF** [comment]
そうなんだ

**Comment by momeemt** [comment]
おーみーさんに新しい学びを提供できたようでよかったです

**Comment by s7tya** [comment]
@momeemt @AumyF @abap34  4日、昼でも良かったりします？

**Comment by AumyF** [comment]
俺が起きれたらいいですよ

**Comment by s7tya** [comment]
猫に会いに行くの6日にしたからやっぱり夜でもなんでもいいですSORRY

**Comment by momeemt** [comment]
絶対に起きれないので夜希望ですが終電が早いです（何もかも最悪

**Comment by momeemt** [comment]
これ何時にしますか？

**Comment by momeemt** [comment]
決まった気でいたけど、ご飯やさんと集合場所も決まっていなかった

**Comment by AumyF** [comment]
実は何も決まってないらしいです

**Comment by abap34** [comment]
大岡山 とりや

**Comment by momeemt** [comment]
採用　大岡山 5時半集合で

**Comment by s7tya** [comment]
OK

**Comment by AumyF** [comment]
カス

**Comment by AumyF** [comment]
午前ですか？

**Comment by momeemt** [comment]
はい

**Comment by abap34** [comment]
GWだし予約した方が良さそう

**Comment by s7tya** [comment]
そんな社会性あったら前日夜まで場所決まってないことないよ

**Comment by momeemt** [comment]
予約しました

**Comment by s7tya** [comment]
社会性がありすぎる

**Comment by momeemt** [comment]
そりゃどうも

**Comment by AumyF** [comment]
大岡山来たけど誰もいねえ

**Comment by momeemt** [comment]
それやるためだけに6時まで起きてたんだ

**Comment by s7tya** [comment]
棘がありすぎる

**Comment by AumyF** [comment]
普通に寝れなかった

**Comment by AumyF** [comment]
舐めるなよ

**Comment by s7tya** [comment]
もうそろそろ支度したほうがいいですよ

**Comment by momeemt** [comment]
何時に出たらいいのかな〜と思って調べたら既に間に合わない時間になってた

**Comment by momeemt** [comment]
ごめんけど間に合わなかったら18:00に予約したアサダです、1人は後から来ます的な事を言ってくれると助かります

**Comment by s7tya** [comment]
了解です

**Comment by s7tya** [comment]
パソコン捏ねるのが楽しくなってきて困った

**Comment by AumyF** [comment]
俺もなんか自宅でクネクネしてたら30分ぐらい遅れそう

**Comment by momeemt** [comment]
渋滞してて終わってる

**Comment by abap34** [comment]
コンカタが佳境

**Comment by momeemt** [comment]
人の出発状況によって予約時間の変更が現実味を帯びてくるが、どうですか

**Comment by s7tya** [comment]
1720には駅着くけどabapさんは？

**Comment by AumyF** [comment]
着

**Comment by momeemt** [comment]
余裕持って間に合うんかい

**Comment by momeemt** [comment]
えー、バスが35分遅延して今東京駅に着きました（キレそう）

**Comment by s7tya** [comment]
18:30にしようね〜(?)

**Comment by momeemt** [comment]
大変申し訳ありません（先入っておいてください）

**Comment by s7tya** [comment]
OK！

**Comment by momeemt** [comment]
たのしかったです
