### ISSUE TITLE
ピザパ

### ISSUE THREAD

**Issue by s7tya** [momeemt/momeemt#8]
ピザパ at 町田 in SUMMER
CC: @aumyf @abap34

**Comment by s7tya** [comment]
![5000choyen](https://github.com/momeemt/momeemt/assets/43488453/02dc6b6c-49f0-43b0-bf17-02c2e0e186d3)

**Comment by AumyF** [comment]
08/20-27ぐらいまで予定あり
他なんか予定あった気もするけど管理してないからよくわかんない

**Comment by s7tya** [comment]
abap34だけアサインされてなくてかわいそう

**Comment by momeemt** [comment]
Issueに関係してないユーザをassigneeにするやり方がわからなかったワ

**Comment by s7tya** [comment]
彼には関係ないもんね

**Comment by momeemt** [comment]
普通に可哀想なのでやめた方がいいですよ

**Comment by AumyF** [comment]
てか夏にピザでいいの？暑くない？うどんとかにせん？

**Comment by momeemt** [comment]
ピザパ、みんなでご飯を食べるくらいの意味だと思ってた

**Comment by AumyF** [comment]
HTTPってことですね　理解しました

**Comment by abap34** [comment]
寿司がいい　さすがに

**Comment by s7tya** [comment]
ピザ食べるぞ

**Comment by momeemt** [comment]
ピザに決定

**Comment by abap34** [comment]
なんでだよ

**Comment by abap34** [comment]
寿司の出前がいい

**Comment by momeemt** [comment]
取りに行ける距離

**Comment by abap34** [comment]
明確な文を書いて

**Comment by momeemt** [comment]
abap34の読解力を信頼して文書いてるんだからそれに応えてほしい

**Comment by AumyF** [comment]
間を取ってツナピザ

**Comment by abap34** [comment]
(笑)

**Comment by momeemt** [comment]
ユーモアのAumyFと言われるだけあるな

**Comment by AumyF** [comment]
abap34程度の読解力があればaumy_fとs7tyaにも通じる、すなわちabap34はこの中で一番読解力が低いって言われてますよ

**Comment by abap34** [comment]
これ開催どこ想定ですか？s7tya？momeemt？imagine the future?

**Comment by AumyF** [comment]
ユーモアセンスを褒められたところにユーモア重ねる形になって最悪

**Comment by momeemt** [comment]
imagine the futureは暑すぎるし涼しい場所は治安が悪い

**Comment by abap34** [comment]
お前の家とかね

**Comment by momeemt** [comment]
二度と来るな

**Comment by AumyF** [comment]
WORD部屋ってエアコンないんですか？なさそうではある

**Comment by momeemt** [comment]
あるけど今ワ部屋史上一番治安が悪い

**Comment by abap34** [comment]
町田大学って寿司食べる部屋もないのか

**Comment by abap34** [comment]
哀れ

**Comment by momeemt** [comment]
まあ天下の東京科学大学と比べたらそらね

**Comment by abap34** [comment]
"まだ”ne

**Comment by AumyF** [comment]
治安が悪い、どんな感じですか？紛争？

**Comment by s7tya** [comment]
僕の描いたモミマウが何名かいる　本人は来ないのに

**Comment by abap34** [comment]
(笑)

**Comment by AumyF** [comment]
影武者？

**Comment by s7tya** [comment]
@momeemt @AumyF 12,13どっちかどう？ 13ならなお良い

**Comment by s7tya** [comment]
ERSとA&D入門がなければ7日でもいいが、要相談

**Comment by abap34** [comment]
7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日7日

**Comment by AumyF** [comment]
7じゃないと無理なら仕事休むが休日か水曜が空いてるならそっちのほうが助かりがあります

**Comment by momeemt** [comment]
13になったって話は共有されてるん？

**Comment by AumyF** [comment]
俺を外して話を進めたってことですか？

**Comment by s7tya** [comment]
7日予定入ったから無理

**Comment by AumyF** [comment]
質問に答えてください

**Comment by s7tya** [comment]
じゃあもみやまのに「されていません」と回答してから聞き直してください

**Comment by AumyF** [comment]
![Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).](https://github.com/momeemt/momeemt/assets/46275902/0e358063-1608-4c35-89ca-b28f6bc24a77)

**Comment by momeemt** [comment]
s7tyaの方がレスバ強いことってあるんだ

**Comment by AumyF** [comment]
煽られてますよ @s7tya

**Comment by s7tya** [comment]
えへへ

**Comment by momeemt** [comment]
キツ

**Comment by AumyF** [comment]
ね

**Comment by AumyF** [comment]
13ド雨らしい

**Comment by momeemt** [comment]
完全に日頃の行いすぎる

**Comment by momeemt** [comment]
あでも特に変更予定はありませんのでド雨の中お越しくださいませ

**Comment by AumyF** [comment]
町田ならいいよ

**Comment by momeemt** [comment]
正直、13日につくば戻って他2人と一緒に東京戻るから東京でもいいです

**Comment by AumyF** [comment]
じゃあ町田で

**Comment by momeemt** [comment]
@abap34 @s7tya 町田になりました

**Comment by s7tya** [comment]
おい

**Comment by s7tya** [comment]
ピザパではあるんですよね？？？

**Comment by s7tya** [comment]
それならいいです

**Comment by AumyF** [comment]
ピザでもいいけどどこで食べるんです？サイゼ？

**Comment by s7tya** [comment]
そうなんだよね

**Comment by s7tya** [comment]
ピザじゃなかったら欠席するくらいにはピザパを楽しみにしている ドミノ・ピザ！のピザが食べたい

**Comment by momeemt** [comment]
ピザならつくばがいいです❗️

**Comment by momeemt** [comment]
普通にピザじゃないと思ってました

**Comment by AumyF** [comment]
終わった

**Comment by AumyF** [comment]
じゃあ椎名はつくばでピザ食べて俺たちは町田でなんか食べるか

**Comment by s7tya** [comment]
つくばにしよう

**Comment by AumyF** [comment]
雨~~~~~~~~~~~~~~~~~

**Comment by s7tya** [comment]
外出て野球する野球少年abap34には影響あるかもしれないけどオタクは雨でも室内でパソコンするだけだから大差ないよ

**Comment by AumyF** [comment]
どういうこと？笑

**Comment by momeemt** [comment]
文字読めない？笑

**Comment by AumyF** [comment]
や、雨の中外出するのキツいって話なのになんで普段の雨の日の過ごし方の話されてるのかなって

**Comment by momeemt** [comment]
偏屈だからじゃない？

**Comment by AumyF** [comment]
さすがs7tyaの心理に詳しい

**Comment by momeemt** [comment]
ｼｲﾅちゃんとは喧嘩するほど仲がいいからネ(^_-)-☆

**Comment by abap34** [comment]
ピザがつくば　どちらかは満たされていて欲しい

**Comment by momeemt** [comment]
13日 19:00から とりや 予約していいですか？

**Comment by AumyF** [comment]
鳥刺しをこの頻度で食べるとそのうちギランバレーで死ぬ

**Comment by abap34** [comment]
いつになったらピザ食うんだ

**Comment by s7tya** [comment]
<img width="337" alt="image" src="https://github.com/momeemt/momeemt/assets/53410646/94205552-7f05-4651-9c63-52d62cb30781">

**Comment by s7tya** [comment]
普通に、外で遊ぶわけでもないなら別に雨でも良くないですか？

**Comment by s7tya** [comment]
てか移動が問題ならどちらかは結局雨の日に外出しなければならないんだよな......

**Comment by momeemt** [comment]
なんかディーエックスの観点からオンラインにした方が移動にかかる消費電力を抑えられてSDGsにも貢献できるかもしれませんね

**Comment by AumyF** [comment]
パソコンで通話するほうが資源使ってると思いますよ

**Comment by momeemt** [comment]
推測するな、計測せよ

**Comment by AumyF** [comment]
消費電力うんぬん、もみやまさんが先に言い出したことですよね

**Comment by momeemt** [comment]
移動にかかる電力が抑えられること自体は事実で嘘は言ってないので、パソコンで通話する方が資源使ってるかどうかはおーみーが確認してください

**Comment by AumyF** [comment]
はい、確かに移動にかかる電力が抑えられるのはそうかと思いますが、リモート会が総合的にSDGsに貢献するかについては、パソコンで通話することとの比較を行わないと貢献するとは主張できないのでは？

**Comment by momeemt** [comment]
俺は論理が破綻していても主張して良いと思っています

**Comment by AumyF** [comment]
わかるよ

**Comment by s7tya** [comment]
おしまいすぎる　これどうしますか？僕も明日東京にいるからとりやなら早めに決めたいけど、それなら夏にちゃんとピザパはしたい

**Comment by AumyF** [comment]
大岡山行く労力は0.8つくばなのでつくばピザパでもいいですよ

**Comment by momeemt** [comment]
明日、筑波にしろ東京にしろ午後大雨っぽいです
筑波に戻ってきたのでそちらの方がありがたいですがそもそも台風来てるので日時変更の線もあるかなとは思います（電車止まったら詰むので）

**Comment by s7tya** [comment]
ピザパ！！！！！！！！！！
まあでもたしかにリスケもありですね、14,15,18,26空いてます

**Comment by abap34** [comment]
26がいい

**Comment by abap34** [comment]
ても、大雨で電車止まると、ウケるよ

**Comment by AumyF** [comment]
- 14, 15…仕事休めなくはない
- 18…空かない
- 26…旅行

いかがでしたか？

**Comment by momeemt** [comment]
15, 26は予定ある 14は大丈夫です

あと、予報が変わって雨じゃないかもしれない

**Comment by momeemt** [comment]
18、18:30-19:00だけ別のmtgやってていいなら🆗

**Comment by abap34** [comment]
20までは無理そう　忙しい

**Comment by abap34** [comment]
zoom飲み？

**Comment by abap34** [comment]
しか残っていませんか？

**Comment by abap34** [comment]
Zoom飲み会のやり方【簡単！無料ですぐ使える】
https://virtualcruise.jp/knowhow/1048/

**Comment by momeemt** [comment]
めっちゃ分かりやすい！笑
さすがabapくんだね、パソコンの学部？に通ってるんだっけ？笑

**Comment by momeemt** [comment]
Zoomか台風ピザパか、終わりの2択だ…

**Comment by abap34** [comment]
ここで話してても一生決まらないので一旦集合しませんか

**Comment by AumyF** [comment]
町田ならいいよ

**Comment by momeemt** [comment]
堂々巡り

**Comment by s7tya** [comment]
台風ピザパしようよ

**Comment by AumyF** [comment]
つくば、椎名すぐ着くのが気に食わないんだよな　ずるい　電車で2時間の苦しみを味わってほしい

**Comment by AumyF** [comment]
というか集合何時？ここ数日睡眠が終わっているのですが。

**Comment by momeemt** [comment]
まあ前回東京だったからな...という気はせんでもない

**Comment by momeemt** [comment]
レポート終わってないから夜とかだと助かる

**Comment by AumyF** [comment]
今から寝るので夕方〜夜でお願いします

**Comment by abap34** [comment]
集合、全然インターネット上の話のつもりではあったが
あと俺も今から寝ます

**Comment by s7tya** [comment]
健康なので今起きた、19時つくばとかにしたら良いなどの案

**Comment by s7tya** [comment]
駅まで迎えに行きますよ

**Comment by momeemt** [comment]
4人中3人が5時台に寝てるけど果たして本当に開催されるのかワクワクしてきた

**Comment by momeemt** [comment]
19時了解です、場所どこにする？
大学でも良いし、場所がない場合はうちでも大丈夫です、その他の場所でも（こだわりないので）

**Comment by s7tya** [comment]
WORDでいいならWORDでもよさそうだし、もみ家がフリーなら行ってみたい気持ちもあります
あと19時って言ったけど19だと遅すぎますか？でも彼らが起きるの14～15時でだらだら支度してたらそれくらいになりそうな気もするんですよね...

**Comment by momeemt** [comment]
いや　まあ　かなりそう思います　18時目標くらいの感じで来てくれたらちょうど良いとは思います

**Comment by AumyF** [comment]
運が良かったので起きたぜ19時了解

**Comment by s7tya** [comment]
18時に着くように16時くらいには家出なね

**Comment by momeemt** [comment]
abapの起床力に掛かってるな

**Comment by s7tya** [comment]
19時になったら早食い大会して遅れてきた犬がつく頃には皿だけにしておこう

**Comment by s7tya** [comment]
<img width="191" alt="image" src="https://github.com/momeemt/momeemt/assets/53410646/b3a22e3d-7e87-4e45-8612-cdbd21052561">

**Comment by momeemt** [comment]
なによりです

**Comment by s7tya** [comment]
でもどちらかといえばaumy_f二度寝大会のほうが怖くないですか？

**Comment by abap34** [comment]
できれば作業しながら行きたいんだけど東京駅でバス乗り場に間違いなく行く自信ない

**Comment by momeemt** [comment]
バスは結構来るから大丈夫 八重洲南口です

**Comment by AumyF** [comment]
起床 (3)

**Comment by s7tya** [comment]
30分で支度、家を出る

**Comment by abap34** [comment]
帰るの全然絶望なので泊まっていい？
いいよ
ありがとう…

**Comment by AumyF** [comment]
草

**Comment by momeemt** [comment]
寝袋持ってきて

**Comment by s7tya** [comment]
買ってもってきますね！

**Comment by momeemt** [comment]
さっきGPUドライバ入れたらUbuntuが起動しなくなったのでエンジニアの皆様におかれましてはお力添えをいただけますとありがたいです.............................

**Comment by momeemt** [comment]
部屋が狭いです

**Comment by s7tya** [comment]
諦めて再インストール

**Comment by momeemt** [comment]
期末レポートを途中までやってて諦めきれなくて...

**Comment by momeemt** [comment]
なんかストレージを維持しつつ再インストールできるっぽいけど全然やらかしそうで怖い　あとUbuntuのインストールメディアが生活課サーバに放置したままだ...

**Comment by s7tya** [comment]
期末レポート、締切いつですか？

**Comment by momeemt** [comment]
17 23:59 ですね

**Comment by AumyF** [comment]
ぱちょこんもっていくか迷うな

**Comment by AumyF** [comment]
そういえば雨だわ

**Comment by momeemt** [comment]
パソコンがないオタクの集まりって10分くらいで会話続かなくなって解散しちゃうイメージある

**Comment by s7tya** [comment]
ならサンクコスト云々ということで一旦諦めてNixOSを入れるなど

**Comment by momeemt** [comment]
正直あり

**Comment by AumyF** [comment]
GPUドライバがってことは謎半メですよね？NixOSって対応してんのそれ

**Comment by AumyF** [comment]
わざわざ茨城まで行って2時間で帰るのムカつくので泊まりたさはわずかにあるな

**Comment by abap34** [comment]
つくばエクスプレスだと19:08に合宿所で、高速バスだと19:20に大学なんだけど、後者は17分で駅からバス乗り場まで行かなきゃでかなり自信ない

**Comment by momeemt** [comment]
普通にNVIDIA　aptからドライバ入れて再起動したらぶっ壊れた　知識が足りず

**Comment by momeemt** [comment]
> わざわざ茨城まで行って2時間で帰るのムカつくので泊まりたさはわずかにあるな

確かにね　まあ全然どうぞ

**Comment by momeemt** [comment]
> 後者は17分で駅からバス乗り場まで行かなきゃでかなり自信ない

今の時間だとどうかわからないけど高速バス、行列できるから遅く行くと乗れないこともあるよ

まあどのみち注文が滞りなく行われるわけないからゆっくり来てください

**Comment by abap34** [comment]
じゃあ18:45につくば駅行きます

**Comment by abap34** [comment]
寿司食べたくなってきた

**Comment by s7tya** [comment]
無理

**Comment by momeemt** [comment]
ハーフ&ハーフにすれば？

**Comment by AumyF** [comment]
確かにね

**Comment by AumyF** [comment]
19時06分につくば駅着きうります

**Comment by momeemt** [comment]
片付け終わってたら7時くらいにつくば駅行きます、終わらなければいきません

**Comment by s7tya** [comment]
7時に家を出ます

**Comment by abap34** [comment]
守谷で全員降りたんだけど、もしかしてつくばって不人気？

**Comment by momeemt** [comment]
爆速で40分も東京から北へ輸送される人間がいっぱいいたら嫌じゃない？

**Comment by s7tya** [comment]
守谷まで行ったらもう爆速で東京から北へ輸送される嫌さの90%くらいは満たされてない？

**Comment by abap34** [comment]
@momeemt 19:08に合宿所

**Comment by momeemt** [comment]
みんな一斉に来るのかと思った

**Comment by momeemt** [comment]
ok

**Comment by momeemt** [comment]
abapのみ？だよね？

**Comment by s7tya** [comment]
え、僕も直で行こうかな

**Comment by s7tya** [comment]
全然駅集合だと思ってた

**Comment by momeemt** [comment]
オーミーエフ、合宿所まで来れる？

**Comment by momeemt** [comment]
合宿所ってバス停があって、筑波大学循環の多分左回りで来れるよ

**Comment by AumyF** [comment]
Googleマップに裏切られたので15分にバ駅着です

**Comment by AumyF** [comment]
30分発の左回りに乗ります

**Comment by s7tya** [comment]
着いた気がする

**Comment by s7tya** [comment]
誰もいないんだけど

**Comment by momeemt** [comment]
どこに着いたの？合宿所の話なら僕とabapはもう家に帰りました

**Comment by s7tya** [comment]
理解、家まで来ました

**Comment by s7tya** [comment]
入口が不明

**Comment by AumyF** [comment]
平日ダイヤ見ててうつ病になった

**Comment by AumyF** [comment]
とりあえず合宿所に行けばいいんですよね

**Comment by momeemt** [comment]
はい　お願いします

**Comment by AumyF** [comment]
@momeemt 爆着

**Comment by momeemt** [comment]
迎えに行きます

**Comment by momeemt** [comment]
@AumyF @abap34 @s7tya https://garticphone.com/ja/?c=03a2878f26

**Comment by s7tya** [comment]
良い会でした　ありがとうございました
