### ISSUE TITLE
筑波大学AC入試について

### ISSUE THREAD

**Issue by shiomanju** [momeemt/momeemt#9]
@momeemt 
突然の連絡失礼いたします。高校3年の寺嶋と申します。
現在、筑波大学情報学群情報科学類のAC入試を目指しており、noteで発信されているのを見て、連絡させていただきました。
もしよろしければ自己推薦書を見せていただけませんでしょうか。
関西在住のため周りに聞ける人がおらず、最終的にどのようにまとめるか迷っております。
よろしくお願い致します。

**Comment by momeemt** [comment]
@terayumi 応援しています！リポジトリに招待しておきましたので、また何か執筆する際に悩んでいることがあればそちらのIssueでご質問ください〜

**Comment by shiomanju** [comment]
ありがとうございます。
